CREATE TABLE IF NOT EXISTS movimientos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cuenta_numero INTEGER NOT NULL,
    monto INTEGER NOT NULL,
    tipo_operacion TEXT NOT NULL,
    hora DATETIME DEFAULT CURRENT_TIMESTAMP
);
